<a href="https://colab.research.google.com/github/RobotMa/PyTorch/blob/master/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121




1.   Tensor not the right type
2.   Tensor not the right shape
3.   Tensor not on the right device



### Manipulating Tensors (tensor operations)
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [3]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [ ]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")
print(f"Divide: {tensor / tensor}")
print(f"Dot product: {torch.matmul(tensor, tensor)}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])
Divide: tensor([1., 1., 1.])
Dot product: 1400


In [ ]:
%%time
torch.matmul(tensor, tensor)
tensor @ tensor

CPU times: user 544 µs, sys: 0 ns, total: 544 µs
Wall time: 428 µs


tensor(1400)

In [12]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]], dtype=torch.float32)

In [10]:
tensor_A.T, tensor_A.T.shape

(tensor([[1., 3., 5.],
         [2., 4., 6.]]),
 torch.Size([2, 3]))

In [11]:
tensor_A, tensor_A.shape

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 torch.Size([3, 2]))

In [21]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [20]:
torch.min(x=tensor), tensor.min()

tensor.type(torch.float32).mean()

tensor(45.)

In [25]:
x.argmin()
x[0], x[9], x.argmax(), x.sum()

(tensor(0), tensor(90), tensor(9), tensor(450))

In [26]:
y = torch.stack((x,x))
y

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [27]:
y.sum()

tensor(900)

In [31]:
y.shape
y_reshaped = y.reshape(10, 2)
y_reshaped, y_reshaped.shape

(tensor([[ 0, 10],
         [20, 30],
         [40, 50],
         [60, 70],
         [80, 90],
         [ 0, 10],
         [20, 30],
         [40, 50],
         [60, 70],
         [80, 90]]),
 torch.Size([10, 2]))

In [33]:
z = y.view(10, 2)
z[:, 1] = 5
z

tensor([[ 0,  5],
        [20,  5],
        [40,  5],
        [60,  5],
        [80,  5],
        [ 0,  5],
        [20,  5],
        [40,  5],
        [60,  5],
        [80,  5]])

In [34]:
y.permute(1, 0)
y

tensor([[ 0,  5, 20,  5, 40,  5, 60,  5, 80,  5],
        [ 0,  5, 20,  5, 40,  5, 60,  5, 80,  5]])

In [36]:
arrany = np.arange(1.0, 8.0)
arrany.dtype
tensor = torch.from_numpy(arrany)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [5]:
torch.cuda.is_available()
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
tensor =  torch.ones(7,7)
print(tensor, device)

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]]) cuda


In [8]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]], device='cuda:0')

In [9]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)